// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webshop.Api.Contexts;

#nullable disable

namespace Webshop.Api.Migrations
{
    [DbContext(typeof(WebshopContext))]
    [Migration("20230131085350_AddedStatusFieldToOrderAndDefaultData")]
    partial class AddedStatusFieldToOrderAndDefaultData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Webshop.Api.Entities.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Webshop.Api.Entities.Category", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = "Wheel Base"
                        },
                        new
                        {
                            Id = "Pedals"
                        },
                        new
                        {
                            Id = "Steering Wheels"
                        });
                });

            modelBuilder.Entity("Webshop.Api.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Webshop.Api.Entities.OrderProduct", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("OrderId", "ProductVariantId");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("Webshop.Api.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9c5f329d-1ed1-4d09-8a15-d056a5df6599"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "All the variants of Simucube 2 use industrial quality electronics, advanced software and firmware, and are built with high-quality materials for durability and long-lasting performance. They also have a wide range of compatibility with various sim racing software and games.",
                            IsActive = true,
                            Name = "Simucube 2"
                        },
                        new
                        {
                            Id = new Guid("297c7eda-33c4-47d3-ab1a-60f5d477dd13"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "The Fanatec Clubsport v3 pedals are a high-end set of pedals designed for use with racing simulators. They feature a durable aluminum construction and are fully adjustable to fit the user's preferences. The pedals include a load cell brake, which provides precise braking force feedback, as well as an adjustable brake stiffness. The pedals also feature a realistic and adjustable clutch, allowing for smooth gear changes. Additionally, the pedals have a vibration motor built-in to provide even more immersive feedback. These pedals are compatible with most racing simulators and are a great choice for serious sim racers looking for the most realistic and immersive experience.",
                            ImageUrl = "https://fanatec.com/media/image/60/ef/a1/CSP_V3_prime2_1280x1280.jpg",
                            IsActive = true,
                            Name = "ClubSport Pedals V3"
                        },
                        new
                        {
                            Id = new Guid("c0b5b2f5-0b1f-4b5e-8b1a-5b5b5b5b5b5b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://fanatec.com/media/image/9c/70/21/Product_Page_top_banner_Podium_SW_BMW_M4_GT3_Front_1280x1280.jpg",
                            IsActive = true,
                            Name = "Podium BMW M4 GT3"
                        });
                });

            modelBuilder.Entity("Webshop.Api.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("9c5f329d-1ed1-4d09-8a15-d056a5df6599"),
                            CategoryId = "Wheel Base"
                        },
                        new
                        {
                            ProductId = new Guid("297c7eda-33c4-47d3-ab1a-60f5d477dd13"),
                            CategoryId = "Pedals"
                        },
                        new
                        {
                            ProductId = new Guid("c0b5b2f5-0b1f-4b5e-8b1a-5b5b5b5b5b5b"),
                            CategoryId = "Steering Wheels"
                        });
                });

            modelBuilder.Entity("Webshop.Api.Entities.ProductOffer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("OffPercentage")
                        .HasColumnType("float");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.ToTable("ProductOffers");
                });

            modelBuilder.Entity("Webshop.Api.Entities.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double?>("PurchasePrice")
                        .HasColumnType("float");

                    b.Property<double>("SellingPrice")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("de880055-3788-4802-8875-4a4dd0a09e5b"),
                            Description = "The SimuCube 2 Sport is the entry-level variant and is designed for entry-level and club-level sim racers. It features a compact design and a torque of up to 10Nm.",
                            IsActive = true,
                            Name = "Sport",
                            ProductId = new Guid("9c5f329d-1ed1-4d09-8a15-d056a5df6599"),
                            PurchasePrice = 800.0,
                            SellingPrice = 1295.0,
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("835ec654-43e5-49c6-abe6-ffb20d274f52"),
                            Description = "The SimuCube 2 Pro is designed for professional and semi-professional sim racers. It features a torque of up to 20Nm and a higher level of customization options.",
                            IsActive = true,
                            Name = "Pro",
                            ProductId = new Guid("9c5f329d-1ed1-4d09-8a15-d056a5df6599"),
                            PurchasePrice = 1000.0,
                            SellingPrice = 1495.0,
                            Stock = 10
                        },
                        new
                        {
                            Id = new Guid("5833c2fb-0aec-4435-b16c-e1146502ce62"),
                            Description = "The SimuCube 2 Ultimate is the top-of-the-line variant and is designed for elite sim racers. It features a torque of up to 32Nm and the most advanced customization options.",
                            IsActive = true,
                            Name = "Ultimate",
                            ProductId = new Guid("9c5f329d-1ed1-4d09-8a15-d056a5df6599"),
                            PurchasePrice = 2000.0,
                            SellingPrice = 3295.0,
                            Stock = 4
                        },
                        new
                        {
                            Id = new Guid("b954ba3b-5668-4e43-b183-4e3af98cf74c"),
                            IsActive = true,
                            Name = "Default",
                            ProductId = new Guid("297c7eda-33c4-47d3-ab1a-60f5d477dd13"),
                            PurchasePrice = 300.0,
                            SellingPrice = 399.0,
                            Stock = 25
                        },
                        new
                        {
                            Id = new Guid("3be4fb1f-edd1-4ac7-b64e-d10eaf1f2b1e"),
                            IsActive = true,
                            Name = "Inverted",
                            ProductId = new Guid("297c7eda-33c4-47d3-ab1a-60f5d477dd13"),
                            PurchasePrice = 400.0,
                            SellingPrice = 599.0,
                            Stock = 4
                        },
                        new
                        {
                            Id = new Guid("ec2e9348-3b59-4232-9094-2597ce777cfe"),
                            IsActive = true,
                            Name = "Default",
                            ProductId = new Guid("c0b5b2f5-0b1f-4b5e-8b1a-5b5b5b5b5b5b"),
                            PurchasePrice = 1100.0,
                            SellingPrice = 1499.0,
                            Stock = 1
                        });
                });

            modelBuilder.Entity("Webshop.Api.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AddressId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getutcdate()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4ac4752c-45a0-4677-845c-0b9849312bde"),
                            CreatedAt = new DateTime(2023, 1, 31, 8, 53, 50, 725, DateTimeKind.Utc).AddTicks(6719),
                            Email = "admin@gunthers-sim-gear.com",
                            FullName = "Admin",
                            IsActive = true,
                            PasswordHash = "jkDmQg/7UaOaQzQNRyOxS6T9hrgh00nCIE+VSzAZoEBf6OG1hOvMsEaSrEwJrLt779Mpizvm6omg7VWLAz3ieQ==",
                            PasswordSalt = "2e961c5efd494449b0125a68fadd45dc",
                            Role = 2
                        });
                });

            modelBuilder.Entity("Webshop.Api.Entities.Order", b =>
                {
                    b.HasOne("Webshop.Api.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webshop.Api.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Webshop.Api.Entities.OrderProduct", b =>
                {
                    b.HasOne("Webshop.Api.Entities.Order", null)
                        .WithMany("Products")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webshop.Api.Entities.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("Webshop.Api.Entities.ProductCategory", b =>
                {
                    b.HasOne("Webshop.Api.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Webshop.Api.Entities.Product", "Product")
                        .WithMany("Categories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Webshop.Api.Entities.ProductOffer", b =>
                {
                    b.HasOne("Webshop.Api.Entities.ProductVariant", null)
                        .WithMany("Offers")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Webshop.Api.Entities.ProductVariant", b =>
                {
                    b.HasOne("Webshop.Api.Entities.Product", null)
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Webshop.Api.Entities.User", b =>
                {
                    b.HasOne("Webshop.Api.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Webshop.Api.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Webshop.Api.Entities.Order", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Webshop.Api.Entities.Product", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Webshop.Api.Entities.ProductVariant", b =>
                {
                    b.Navigation("Offers");
                });
#pragma warning restore 612, 618
        }
    }
}
